title: CollectiveOrders
modelClass: AramLoosman\Foodcoop\Models\CollectiveOrder
list: $/aramloosman/foodcoop/models/collectiveorder/columns.yaml
recordUrl: 'aramloosman/foodcoop/collectiveorders/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
